import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '@/components/Card/index'
import Link from 'next/link'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  console.log(data);
  const [information, setInformation] = useState([...data]);

  return (
    <>
      <Head>
        <title>Team Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.nav}>
          <span><Link href="/">Home</Link></span>
          <span><Link href="about">About</Link></span>
        </nav>
        <div className={styles.content}>
            {
              information && information.map((info, index) => {
                if(info.department.toLowerCase() === "business"){
                  return(
                    // <div key={index}>{info.degree}</div>
                    <Card key={index} degree={info.degree}  studentNumber={info.studentNumber} />
                  )
                }
                if(info.department.toLowerCase() === "computing"){
                  return(
                    // <div key={index}>{info.degree}</div>
                    <Card key={index} degree={info.degree} studentNumber={info.studentNumber} />
                  )
                }
              })
            }
            <div className={styles.empty}>...</div>
        </div>
        {/* <img className={styles.bgImage} src={'icon/pixel_bg.svg'}></img> */}
      </main>

    </>
  )
}
